"""Add blog models

Revision ID: 3f745beeb4f1
Revises: 717a207b919a
Create Date: 2026-05-04 07:25:18.151957

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '3f745beeb4f1'
down_revision = '717a207b919a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_subscribers',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_subscribers'))
    )
    op.create_index(op.f('ix_blog_subscribers_email'), 'blog_subscribers', ['email'], unique=True)
    op.create_table('blog_posts',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('primary_image', sa.String(length=500), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('read_time', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['blog_categories.id'], name=op.f('fk_blog_posts_category_id_blog_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_posts'))
    )
    op.create_index(op.f('ix_blog_posts_category_id'), 'blog_posts', ['category_id'], unique=False)
    op.create_index('ix_blog_posts_created_at', 'blog_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.drop_index('ix_blog_posts_created_at', table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_category_id'), table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_index(op.f('ix_blog_subscribers_email'), table_name='blog_subscribers')
    op.drop_table('blog_subscribers')
    # ### end Alembic commands ###
