"""Add categories model

Revision ID: adceb3b886e3
Revises: 20260415_0001
Create Date: 2026-04-21 18:23:41.728141

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'adceb3b886e3'
down_revision = '20260415_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('categories',
    # sa.Column('name', sa.String(length=255), nullable=False),
    # sa.Column('slug', sa.String(length=255), nullable=False),
    # sa.Column('description', sa.String(length=500), nullable=True),
    # sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    # sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    # )
    # op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    # op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    # op.create_index(op.f('ix_categories_sort_order'), 'categories', ['sort_order'], unique=False)
    with op.batch_alter_table('products') as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_products_category_id_categories'), 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products') as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_products_category_id_categories'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
        batch_op.drop_column('category_id')
    # op.drop_index(op.f('ix_categories_sort_order'), table_name='categories')
    # op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    # op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    # op.drop_table('categories')
    # ### end Alembic commands ###
